import { ApplicationConfig, provideBrowserGlobalErrorListeners } from '@angular/core';
import { provideRouter } from '@angular/router';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { provideIcons } from '@ng-icons/core';
import { authInterceptor } from '@app/core/auth/auth.interceptor';
import {
  lucideActivity,
  lucideAlertTriangle,
  lucideArrowDown,
  lucideArrowLeft,
  lucideArrowRight,
  lucideAward,
  lucideBarChart3,
  lucideBell,
  lucideBellRing,
  lucideBus,
  lucideCalendar,
  lucideCalendarClock,
  lucideCalendarDays,
  lucideChartLine,
  lucideCheck,
  lucideCheckCircle2,
  lucideClock,
  lucideDoorOpen,
  lucideEye,
  lucideEyeOff,
  lucideFileText,
  lucideHome,
  lucideHotel,
  lucideLayoutDashboard,
  lucideLifeBuoy,
  lucideLoader2,
  lucideLogOut,
  lucideMail,
  lucideMapPin,
  lucideMenu,
  lucideMoon,
  lucideNavigation,
  lucidePencil,
  lucidePlane,
  lucidePlus,
  lucideRoute,
  lucideSearch,
  lucideShieldCheck,
  lucideSparkles,
  lucideStar,
  lucideSun,
  lucideTrendingDown,
  lucideTrendingUp,
  lucideUser,
  lucideUserCheck,
  lucideUserPlus,
  lucideUsers,
  lucideWallet,
  lucideX,
} from '@ng-icons/lucide';

import { routes } from './app.routes';
import { provideClientHydration, withEventReplay } from '@angular/platform-browser';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideRouter(routes),
    provideHttpClient(withInterceptors([authInterceptor])),
    provideClientHydration(withEventReplay()),
    provideIcons({
      lucideHome,
      lucideActivity,
      lucideAlertTriangle,
      lucideArrowDown,
      lucideArrowLeft,
      lucideArrowRight,
      lucideAward,
      lucideBarChart3,
      lucideBell,
      lucideBellRing,
      lucideBus,
      lucideCalendar,
      lucideCalendarClock,
      lucideCalendarDays,
      lucideChartLine,
      lucideCheck,
      lucideCheckCircle2,
      lucideClock,
      lucideDoorOpen,
      lucideEye,
      lucideEyeOff,
      lucideFileText,
      lucideHotel,
      lucideLayoutDashboard,
      lucideLifeBuoy,
      lucideLoader2,
      lucideLogOut,
      lucideMail,
      lucideMapPin,
      lucideMenu,
      lucideMoon,
      lucideNavigation,
      lucidePencil,
      lucidePlane,
      lucidePlus,
      lucideRoute,
      lucideSearch,
      lucideShieldCheck,
      lucideSparkles,
      lucideStar,
      lucideSun,
      lucideTrendingDown,
      lucideTrendingUp,
      lucideUser,
      lucideUserCheck,
      lucideUserPlus,
      lucideUsers,
      lucideWallet,
      lucideX,
    }),
  ],
};
