package com.travelease.backend.busbooking.entity.enums;

public enum BookingEvent {
    BOOKING_CREATED,
    PAYMENT_INITIATED,
    PAYMENT_COMPLETED,
    PAYMENT_FAILED,
    BOOKING_CONFIRMED,
    BOOKING_MODIFIED,
    BOOKING_CANCELLED,
    BOOKING_COMPLETED,
    BOOKING_EXPIRED,
    BOOKING_FAILED,
    TICKET_GENERATED,
    TICKET_REPRINTED,
    // Phase 7 â€“ Refund events
    REFUND_INITIATED,
    REFUND_PROCESSING,
    REFUND_APPROVED,
    REFUND_COMPLETED,
    REFUND_FAILED,
    REFUND_REJECTED
}
